### ISSUE TITLE
[BUG] error MSB3322: Unable to get MD5 checksum for the key file "EnhancedTrafficSign.pfx". Could not find file 'C:\Users\Admin\Source\Repos\Flight-Simulator-Better-Traffic\EnhancedTrafficSign.pfx'.

### ISSUE THREAD

**Issue by sathiathirumal** [GewoonJaap/Flight-Simulator-Better-Traffic#3]
## Description

Unable to build. Get the following error when compiling the .sln with VS2019 Community Edition.

1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(3325,5): error MSB3322: Unable to get MD5 checksum for the key file "EnhancedTrafficSign.pfx". Could not find file 'C:\Users\Admin\Source\Repos\Flight-Simulator-Better-Traffic\EnhancedTrafficSign.pfx'.

## To reproduce

1. Clone the repo in VS2019 (I am using the Community edition).
2. Open the simvars.sln
3. Build the project
4. Hit the error above

## Environment

**Manager version:**
Not applicable?
**FS2020 Version:**
Not applicable

## Screenshots or videos

<details>
<summary>Click to expand</summary>

</details>

**Comment by sathiathirumal** [comment]
Please note: I was able to generate a new cert locally and use that to sign my assembly output. Recommend these instructions be added to the Readme.md. In fact, I will create a pull request for that one.

**Comment by fabioduque** [comment]
I had the same issue with the PFX file.
As a temporary workaround, just to check the project, I believe you can disable the assembly signage.

1. Inside Visual Studio, go to the project properties. 
2. On the "Signing" tab, just uncheck "Sign the assembly". 
3. Build again and it should work.
